const STATE_CARD = "STATE_CARD";

const ACTION_GETALLCARD = "ACTION_GETALLCARD";
const ACTION_GETALLCARD_SUCCESS = "ACTION_GETALLCARD_SUCCESS";
const ACTION_GETALLCARD_FAILURE = "ACTION_GETALLCARD_FAILURE";
const ACTION_GETALLCARD_DEFAULT = "ACTION_GETALLCARD_DEFAULT";

const ACTION_SEARCHCARD = "ACTION_SEARCHCARD";
const ACTION_SEARCHCARD_SUCCESS = "ACTION_SEARCHCARD_SUCCESS";
const ACTION_SEARCHCARD_FAILURE = "ACTION_SEARCHCARD_FAILURE";
const ACTION_SEARCHCARD_DEFAULT = "ACTION_SEARCHCARD_DEFAULT";

const ACTION_SETSEARCHKEYWORD = "ACTION_SETSEARCHKEYWORD";

export default {
  STATE_CARD,

  ACTION_GETALLCARD,
  ACTION_GETALLCARD_SUCCESS,
  ACTION_GETALLCARD_FAILURE,
  ACTION_GETALLCARD_DEFAULT,

  ACTION_SEARCHCARD,
  ACTION_SETSEARCHKEYWORD,
  ACTION_SEARCHCARD_SUCCESS,
  ACTION_SEARCHCARD_FAILURE,
  ACTION_SEARCHCARD_DEFAULT,
};
